# Generated by Django 2.2 on 2018-12-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181228_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNum',
            new_name='RReadNum',
        ),
    ]
