# Generated by Django 2.2 on 2018-12-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181228_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RReadNum',
            new_name='ReSReadNum',
        ),
    ]
