# Generated by Django 2.2 on 2018-12-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181228_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReSReadNum',
            new_name='ReadNum',
        ),
    ]
