# Generated by Django 2.2 on 2018-12-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181228_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
